---
- hosts: [ubuntu_hosts]
  remote_user: ubuntu
  ansible_user: ubuntu
  become: yes
  ansible_become: true
  become_method: sudo
  tasks:
        - name: Create file
          file:
              path: /tmp/yalloo
              state: touch
...
