---
- hosts: [ubuntu_hosts]
  become: yes
  become_user: ubuntu
  become_method: sudo
  tasks:
        - name: Create file
          file:
              path: /tmp/yalloo
              state: touch
...
